Bump every package to version 0.2
ros2-rust/ros2_rust pull request #100
Opened 2022-04-10 12:30 UTC by nnmm

Also, add Nikolai as rclrs author/maintainer

2022-04-11 11:40 UTC, jhdcs commented
This appears good to me! The version "regression" in `rclrs_examples` is just a correction, right?

2022-04-11 11:41 UTC, jhdcs approved these changes

2022-04-11 12:42 UTC, esteve requested changes
Leaving a comment here before this gets merged and I'll add more later, but this PR needs to be split into multiple ones and not ok with the author field. The tradition in ROS is to keep the author field intact, but add maintainers. For example, rclcpp still has Dirk as the sole author, despite William being the most active committee and me being the third. Nevertheless, Jacob should be added as a maintainer as well.

2022-04-12 07:25 UTC, nnmm commented
Ok, sure @esteve. I wasn't clear about the meaning of the author field. I'm making this PR just about the version numbers then.

2022-04-12 10:49 UTC, esteve commented
@nnmm thanks!

2022-04-14 19:29 UTC, nnmm commented
@esteve Done.

2022-04-16 10:52 UTC, nnmm commented
@esteve Could you approve if no further changes are required?

2022-04-17 11:57 UTC, esteve approved these changes

2022-04-17 12:47 UTC, merged