Remove libc dependencies
ros2-rust/ros2_rust pull request #284
Opened 2022-10-16 03:37 UTC by Tacha-S

- Replace libc crate with `std::ffi`
- Remove realloc and memcpy workaround https://github.com/ros2-rust/ros2_rust/issues/215#issuecomment-1279723455

2022-10-16 09:02 UTC, esteve commented
@Tacha-S this is looking great, thanks! Let us know when it's ready for review

2022-10-17 03:46 UTC, Tacha-S commented
I was developing with 1.64.
But unfortunately 1.63(CI version) requires core::ffi instead of std::ffi.

https://doc.rust-lang.org/src/std/ffi/mod.rs.html#157

Which version should be support?

2022-10-17 09:02 UTC, nnmm commented
I don't fully understand – the compiler error sounds like 1.63 has `core::ffi`, but the [release notes](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#c-compatible-ffi-types-in-core-and-alloc) and [`core::ffi` docs](https://doc.rust-lang.org/core/ffi/type.c_short.html) look like that module was introduced with `1.64`? Maybe these types were available but experimental in 1.63.

Either way, I think it would be nice to support 1.63 if it's not too ugly. Maybe that requires using `std::os::raw` after all.

2022-10-17 12:11 UTC, Tacha-S commented
[`core::ffi` was unstable](https://github.com/rust-lang/rust/pull/98315) before 1.64.0.

2022-10-17 12:53 UTC, jhdcs requested changes
Looks pretty good to me! I only saw one spot where a comment's phrasing seemed a little odd.

That being said, a second pair of eyes would be useful, I think. Just in case I missed something.

2022-10-17 12:53 UTC, jhdcs commented on rosidl_generator_rs/resource/msg_rmw.rs.em
> +    // SAFETY: This is safe since a the point is guaranteed to be valid/initialized.
```suggestion
    // SAFETY: This is safe since the pointer is guaranteed to be valid/initialized.
```

2022-10-17 12:53 UTC, nnmm commented on rosidl_runtime_rs/src/traits.rs
> +    fn get_type_support() -> usize;
While we're here – could we make this pointer and the one in the `Service` trait a `*const c_void`?

2022-10-18 12:24 UTC, jhdcs approved these changes
Looks good to me!

@nnmm does everything look okay to you?

2022-10-18 13:39 UTC, nnmm approved these changes
Nice work, thank you! :)

2022-10-18 18:16 UTC, merged