Add the DynamicMessage type itself
ros2-rust/ros2_rust pull request #292
Opened 2022-11-05 18:01 UTC by nnmm

As well as conversion from/to concrete message types.

It's clear logically that the alignment has to be 8, since C messages only contain pointers and primitive types of alignment less than or equal to 8 – with the exception of `long double`. Should we require dynamic messages to be aligned to 16 bytes to support `long double`? Even `test_msgs` doesn't use `long double`.

2022-11-14 12:57 UTC, jhdcs commented
If ROS 2 itself _supports_  `long double`, I'd say yes. If only because we want to match to spec. But I would be fine with just putting in a `TODO<name>:` for it if it's not a regularly used feature.

Do we know what alignment the ROS 2 standard uses, itself? Do different messages have different alignments depending on contents, or do they just make everything aligned to 16 bytes? Or is that a silly question?

2022-11-14 14:19 UTC, jhdcs requested changes
Only saw a single area where I had questions, otherwise this looks pretty good to me!

2022-11-14 16:39 UTC, nnmm commented on rclrs/src/dynamic_message.rs
> +            // SAFETY: The data pointer is supposed to be always valid.
Someone could always create a shared library containing invalid pointers – but there's no way of protecting against that, I think it's just out of scope for Rust's safety guarantees. The same already holds for any of the other libraries that we link against, like `rcl` – if we can't trust those, then it's game over anyway.

2022-11-14 16:42 UTC, nnmm commented
> If ROS 2 itself _supports_ `long double`, I'd say yes. If only because we want to match to spec. But I would be fine with just putting in a `TODO<name>:` for it if it's not a regularly used feature.

I don't know, but you know what, I'll just make it 16 bytes, it doesn't cost us anything really.

> Do we know what alignment the ROS 2 standard uses, itself? Do different messages have different alignments depending on contents, or do they just make everything aligned to 16 bytes? Or is that a silly question?

There is no prescribed alignment, it depends on the contents. So a message containing only `u16` fields would have alignment of 2 bytes for instance.

2022-11-14 16:45 UTC, jhdcs approved these changes

2022-12-12 16:23 UTC, esteve approved these changes

2023-02-19 12:00 UTC, esteve commented
@nnmm do you want to merge this one or shall we wait?

2024-01-09 14:48 UTC, merged