Refactor spin and spin_once to mimic rclcpp's Executor API
ros2-rust/ros2_rust pull request #324
Opened 2023-07-26 15:35 UTC by esteve

Moving `spin` and `spin_once` to a similar API as `rclcpp`'s and `rclpy`'s Executor API allows us to run more than one node in a single program and makes it easier to test `node` behaviors.

2023-07-30 18:32 UTC, esteve commented
@jhdcs @maspe36 these changes are functionally equivalent to what we alredy have now, but add the extra feature of being able to run more than one node in a program (see the example I've added where there's a publisher and two subscriptions). I plan on expanding this to enable multiple implementations of an executor following `rclcpp`/`rclpy`'s approach, but for now I just wanted to get a concrete implementation and then I'll derive traits and other generalizations in a follow-up PR.

This would also allow us to implement composable nodes in the future, but for now the `spin` method in `SingleThreadedExecutor` just takes an `&Arc<Node>`

2023-07-31 12:01 UTC, jhdcs requested changes
Fantastic work!

I only have a couple very-small issues with the comments for `spin` in `lib.rs`. Of the two, I think the potentially-unneeded SAFETY comment is the more important to take a look at, but I still wanted to call out a potential inaccuracy.

But all in all, this is beautifully done, thank you!

2023-08-01 20:45 UTC, esteve commented
@jhdcs thanks for the review!

You're right about the comments, I'll update/remove them.

> But all in all, this is beautifully done, thank you!

These are very kind words, I really appreciate it, thanks 🙂

2023-08-01 20:53 UTC, esteve commented on rclrs/src/lib.rs
>      // SAFETY: No preconditions for this function.
Removed in https://github.com/ros2-rust/ros2_rust/pull/324/commits/921be1743c1951b3f3967ab686c19dc67289ef58

2023-08-01 20:54 UTC, esteve commented on rclrs/src/lib.rs
>  /// This function additionally checks that the context is still valid.
Moved to the appropriate function in https://github.com/ros2-rust/ros2_rust/pull/324/commits/921be1743c1951b3f3967ab686c19dc67289ef58

2023-08-03 18:37 UTC, esteve commented
@jhdcs I've addressed your feedback, could you have another look when you have a moment? Thanks!

2023-08-07 13:26 UTC, jhdcs approved these changes
Looks good to me! Thank you again for this!

2023-08-07 17:25 UTC, merged