Adding a simple helper function for converting `rclrs::Time` to a ros message
ros2-rust/ros2_rust pull request #359
Opened 2024-01-10 09:36 UTC by arjo129

This commit adds a simple conversion function that would converts Time to `builtin_interfaces::msg::Time` like the one in `rclpy`.

2024-01-10 13:38 UTC, jhdcs requested changes
I like this! Nice and simple, easy to understand, and helps the end user to do their job more efficiently. Thank you!

Only catch is that there appears to be some formatting issues that the linter isn't happy about. Would you be able to modify your submission so that the linter lets the rest of the tests run? Apart from that, this looks pretty good to me!

2024-01-11 11:24 UTC, esteve submitted a review, later dismissed
@arjo129 thank you so much! This looks great, I only have one minor style request, but I've approved this PR anyway so that it can be merged

2024-01-11 11:24 UTC, esteve commented on rclrs/Cargo.toml
> +
@arjo129 could you please remove these two extra blank lines? Thanks.

2024-01-12 01:24 UTC, arjo129 commented
Looks like my last commit dismissed the review :shrug: . I'd be happy to make similar PRs for Duration and the time going the other way.

2024-01-12 09:00 UTC, esteve approved these changes
@arjo129 thanks! @jhdcs do you have more feedback?

2024-01-12 13:35 UTC, jhdcs approved these changes
Nope! Looks good to me!

Thank you very much for the contribution!

2024-01-12 13:42 UTC, merged